### ISSUE TITLE
Coordinate label not matching

### ISSUE THREAD

**Issue by MWSchmid** [Lakshay-Anand/chromoMap.github.io#2]
Hi Lakshay

The scaling of the coordinates seems bugged. Take this as example (genomeFile):

NC_044370.1     1       104987320
NC_044371.1     1       101209240
NC_044372.1     1       94670641
NC_044373.1     1       91913879
NC_044374.1     1       88181582
NC_044375.1     1       96346938
NC_044376.1     1       61561104
NC_044377.1     1       79335105
NC_044378.1     1       71238074
NC_044379.1     1       64622176

and for annotation (annotationFile):

AGLc2   NC_044370.1     8131872 8133380 AGLc
AGLc3   NC_044370.1     8153115 8154479 AGLc
COLc1   NC_044370.1     11667764        11671829        COLc
AGLc4   NC_044370.1     22869150        22869806        AGLc

Then do the default plot with 

chromoMap(genomeFile, annotationFile)

Results in an X-axis that goes approx until 110 Mb. The first sequence also goes until there even though it's only 105 Mb long (the others don't match as well).

Best, 

Marc

**Comment by Lakshay-Anand** [comment]
Hello Marc (@MWSchmid ),

Thank you for trying out the package and for reporting the bug. 

Actually, the scale seems to have been buggy for large genomic lengths. The issue originates due to the D3 scaling that is automatically rounding off the max in some cases. I am now discarding the D3 native scale construction method and including a custom method to build scales that will eliminate this issue in the future release.  

I will be releasing the update with this bug fix and some other new features most likely in early November 2021. I will keep you posted on the same. 

Again, thank you!

Regards,

Lakshay
